# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/yiranshen/anaconda3/bin/cmake

# The command to remove a file.
RM = /Users/yiranshen/anaconda3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/yiranshen/Desktop/hello_cnn-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/yiranshen/Desktop/hello_cnn-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/yiranshen/anaconda3/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Users/yiranshen/anaconda3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yiranshen/Desktop/hello_cnn-master/CMakeFiles /Users/yiranshen/Desktop/hello_cnn-master/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yiranshen/Desktop/hello_cnn-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cnn_test

# Build rule for target.
cnn_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cnn_test
.PHONY : cnn_test

# fast build rule for target.
cnn_test/fast:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/build
.PHONY : cnn_test/fast

ActivationLayer.o: ActivationLayer.cpp.o

.PHONY : ActivationLayer.o

# target to build an object file
ActivationLayer.cpp.o:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/ActivationLayer.cpp.o
.PHONY : ActivationLayer.cpp.o

ActivationLayer.i: ActivationLayer.cpp.i

.PHONY : ActivationLayer.i

# target to preprocess a source file
ActivationLayer.cpp.i:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/ActivationLayer.cpp.i
.PHONY : ActivationLayer.cpp.i

ActivationLayer.s: ActivationLayer.cpp.s

.PHONY : ActivationLayer.s

# target to generate assembly for a file
ActivationLayer.cpp.s:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/ActivationLayer.cpp.s
.PHONY : ActivationLayer.cpp.s

ConvolutionLayer.o: ConvolutionLayer.cpp.o

.PHONY : ConvolutionLayer.o

# target to build an object file
ConvolutionLayer.cpp.o:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/ConvolutionLayer.cpp.o
.PHONY : ConvolutionLayer.cpp.o

ConvolutionLayer.i: ConvolutionLayer.cpp.i

.PHONY : ConvolutionLayer.i

# target to preprocess a source file
ConvolutionLayer.cpp.i:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/ConvolutionLayer.cpp.i
.PHONY : ConvolutionLayer.cpp.i

ConvolutionLayer.s: ConvolutionLayer.cpp.s

.PHONY : ConvolutionLayer.s

# target to generate assembly for a file
ConvolutionLayer.cpp.s:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/ConvolutionLayer.cpp.s
.PHONY : ConvolutionLayer.cpp.s

FullConnect.o: FullConnect.cpp.o

.PHONY : FullConnect.o

# target to build an object file
FullConnect.cpp.o:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/FullConnect.cpp.o
.PHONY : FullConnect.cpp.o

FullConnect.i: FullConnect.cpp.i

.PHONY : FullConnect.i

# target to preprocess a source file
FullConnect.cpp.i:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/FullConnect.cpp.i
.PHONY : FullConnect.cpp.i

FullConnect.s: FullConnect.cpp.s

.PHONY : FullConnect.s

# target to generate assembly for a file
FullConnect.cpp.s:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/FullConnect.cpp.s
.PHONY : FullConnect.cpp.s

Layer.o: Layer.cpp.o

.PHONY : Layer.o

# target to build an object file
Layer.cpp.o:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/Layer.cpp.o
.PHONY : Layer.cpp.o

Layer.i: Layer.cpp.i

.PHONY : Layer.i

# target to preprocess a source file
Layer.cpp.i:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/Layer.cpp.i
.PHONY : Layer.cpp.i

Layer.s: Layer.cpp.s

.PHONY : Layer.s

# target to generate assembly for a file
Layer.cpp.s:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/Layer.cpp.s
.PHONY : Layer.cpp.s

Minst.o: Minst.cpp.o

.PHONY : Minst.o

# target to build an object file
Minst.cpp.o:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/Minst.cpp.o
.PHONY : Minst.cpp.o

Minst.i: Minst.cpp.i

.PHONY : Minst.i

# target to preprocess a source file
Minst.cpp.i:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/Minst.cpp.i
.PHONY : Minst.cpp.i

Minst.s: Minst.cpp.s

.PHONY : Minst.s

# target to generate assembly for a file
Minst.cpp.s:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/Minst.cpp.s
.PHONY : Minst.cpp.s

Net.o: Net.cpp.o

.PHONY : Net.o

# target to build an object file
Net.cpp.o:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/Net.cpp.o
.PHONY : Net.cpp.o

Net.i: Net.cpp.i

.PHONY : Net.i

# target to preprocess a source file
Net.cpp.i:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/Net.cpp.i
.PHONY : Net.cpp.i

Net.s: Net.cpp.s

.PHONY : Net.s

# target to generate assembly for a file
Net.cpp.s:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/Net.cpp.s
.PHONY : Net.cpp.s

PoolingLayer.o: PoolingLayer.cpp.o

.PHONY : PoolingLayer.o

# target to build an object file
PoolingLayer.cpp.o:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/PoolingLayer.cpp.o
.PHONY : PoolingLayer.cpp.o

PoolingLayer.i: PoolingLayer.cpp.i

.PHONY : PoolingLayer.i

# target to preprocess a source file
PoolingLayer.cpp.i:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/PoolingLayer.cpp.i
.PHONY : PoolingLayer.cpp.i

PoolingLayer.s: PoolingLayer.cpp.s

.PHONY : PoolingLayer.s

# target to generate assembly for a file
PoolingLayer.cpp.s:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/PoolingLayer.cpp.s
.PHONY : PoolingLayer.cpp.s

ReluLayer.o: ReluLayer.cpp.o

.PHONY : ReluLayer.o

# target to build an object file
ReluLayer.cpp.o:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/ReluLayer.cpp.o
.PHONY : ReluLayer.cpp.o

ReluLayer.i: ReluLayer.cpp.i

.PHONY : ReluLayer.i

# target to preprocess a source file
ReluLayer.cpp.i:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/ReluLayer.cpp.i
.PHONY : ReluLayer.cpp.i

ReluLayer.s: ReluLayer.cpp.s

.PHONY : ReluLayer.s

# target to generate assembly for a file
ReluLayer.cpp.s:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/ReluLayer.cpp.s
.PHONY : ReluLayer.cpp.s

SigmoidLayer.o: SigmoidLayer.cpp.o

.PHONY : SigmoidLayer.o

# target to build an object file
SigmoidLayer.cpp.o:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/SigmoidLayer.cpp.o
.PHONY : SigmoidLayer.cpp.o

SigmoidLayer.i: SigmoidLayer.cpp.i

.PHONY : SigmoidLayer.i

# target to preprocess a source file
SigmoidLayer.cpp.i:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/SigmoidLayer.cpp.i
.PHONY : SigmoidLayer.cpp.i

SigmoidLayer.s: SigmoidLayer.cpp.s

.PHONY : SigmoidLayer.s

# target to generate assembly for a file
SigmoidLayer.cpp.s:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/SigmoidLayer.cpp.s
.PHONY : SigmoidLayer.cpp.s

SoftmaxLayer.o: SoftmaxLayer.cpp.o

.PHONY : SoftmaxLayer.o

# target to build an object file
SoftmaxLayer.cpp.o:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/SoftmaxLayer.cpp.o
.PHONY : SoftmaxLayer.cpp.o

SoftmaxLayer.i: SoftmaxLayer.cpp.i

.PHONY : SoftmaxLayer.i

# target to preprocess a source file
SoftmaxLayer.cpp.i:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/SoftmaxLayer.cpp.i
.PHONY : SoftmaxLayer.cpp.i

SoftmaxLayer.s: SoftmaxLayer.cpp.s

.PHONY : SoftmaxLayer.s

# target to generate assembly for a file
SoftmaxLayer.cpp.s:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/SoftmaxLayer.cpp.s
.PHONY : SoftmaxLayer.cpp.s

TanhLayer.o: TanhLayer.cpp.o

.PHONY : TanhLayer.o

# target to build an object file
TanhLayer.cpp.o:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/TanhLayer.cpp.o
.PHONY : TanhLayer.cpp.o

TanhLayer.i: TanhLayer.cpp.i

.PHONY : TanhLayer.i

# target to preprocess a source file
TanhLayer.cpp.i:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/TanhLayer.cpp.i
.PHONY : TanhLayer.cpp.i

TanhLayer.s: TanhLayer.cpp.s

.PHONY : TanhLayer.s

# target to generate assembly for a file
TanhLayer.cpp.s:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/TanhLayer.cpp.s
.PHONY : TanhLayer.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/cnn_test.dir/build.make CMakeFiles/cnn_test.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... cnn_test"
	@echo "... ActivationLayer.o"
	@echo "... ActivationLayer.i"
	@echo "... ActivationLayer.s"
	@echo "... ConvolutionLayer.o"
	@echo "... ConvolutionLayer.i"
	@echo "... ConvolutionLayer.s"
	@echo "... FullConnect.o"
	@echo "... FullConnect.i"
	@echo "... FullConnect.s"
	@echo "... Layer.o"
	@echo "... Layer.i"
	@echo "... Layer.s"
	@echo "... Minst.o"
	@echo "... Minst.i"
	@echo "... Minst.s"
	@echo "... Net.o"
	@echo "... Net.i"
	@echo "... Net.s"
	@echo "... PoolingLayer.o"
	@echo "... PoolingLayer.i"
	@echo "... PoolingLayer.s"
	@echo "... ReluLayer.o"
	@echo "... ReluLayer.i"
	@echo "... ReluLayer.s"
	@echo "... SigmoidLayer.o"
	@echo "... SigmoidLayer.i"
	@echo "... SigmoidLayer.s"
	@echo "... SoftmaxLayer.o"
	@echo "... SoftmaxLayer.i"
	@echo "... SoftmaxLayer.s"
	@echo "... TanhLayer.o"
	@echo "... TanhLayer.i"
	@echo "... TanhLayer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

